CREATE DATABASE circketsimulation;

CREATE TABLE Accounts (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Email VARCHAR(150),
	RegisteredOn DATETIME,
	LastSeen DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Stats (
	ID INT PRIMARY KEY,
	played INT DEFAULT 0,
	wins INT DEFAULT 0,
	lost INT DEFAULT 0,
	draws INT DEFAULT 0,
	lowest INT DEFAULT 0,
	highest INT DEFAULT 0,
	score INT DEFAULT 0,
	wickets INT DEFAULT 0,
	sixes INT DEFAULT 0,
	fours INT DEFAULT 0,
	balls INT DEFAULT 0,
	FOREIGN KEY (ID) REFERENCES Accounts(ID) ON UPDATE CASCADE
)